/*
 * bench_small_contraction.c
 *
 * Small-scale benchmark / smoke test for run_contraction_einsum.
 *
 * Contraction: "ijab,akbl->klji"   dtype: COMPLEX128
 *   C(k,l,j,i) = sum_{a,b} A(i,j,a,b) * B(a,k,b,l)
 *
 * Default parameters (compile-time):
 *   SMALL_DIM   = 80   (override with -DSMALL_DIM=N)
 *   SMALL_CHUNK = 16   (override with -DSMALL_CHUNK=N)
 *   POOL_CAP_MB = 128  (override with -DPOOL_CAP_MB=N)
 *
 * Default sizes:
 *   Tensor  : 80^4 × 16 B = 655 MB each
 *   Chunks  : 16^4 × 16 B = 1 MiB each  (5^4 = 625 tiles)
 *   Pool cap: 128 MiB  → forces out-of-core even on 64 GB machines
 *
 * Expected result:
 *   C(k,l,j,i) = DIM^2 × (1+0.5i)^2
 *              = DIM^2 × (0.75 + 1.0i)
 *   For DIM=80: 4800.0 + 6400.0i  (every element)
 *
 * Input files are generated by gen_complex_tensor (or gen_data):
 *   ./build/gen_complex_tensor [80 [16 [small]]]
 * This creates small_A.h5 and small_B.h5 in the working directory.
 */

#include "engine.h"
#include "registry.h"
#include "tensor_store.h"
#include <hdf5.h>
#include <complex.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#ifndef SMALL_DIM
#  define SMALL_DIM   80
#endif
#ifndef SMALL_CHUNK
#  define SMALL_CHUNK 16
#endif
#ifndef POOL_CAP_MB
#  define POOL_CAP_MB 128
#endif

#define FILE_A  "small_A.h5"
#define FILE_B  "small_B.h5"
#define FILE_C  "small_C.h5"
#define DSET    "tensor"

/*
 * Expected accumulation: DIM^2 × (1+0.5i)^2 = DIM^2 × (0.75+i)
 */
#define EXPECTED_REAL  ((double)(SMALL_DIM) * (double)(SMALL_DIM) * 0.75)
#define EXPECTED_IMAG  ((double)(SMALL_DIM) * (double)(SMALL_DIM) * 1.0)

static double elapsed_s(const struct timespec *a, const struct timespec *b)
{
    return (double)(b->tv_sec  - a->tv_sec)
         + (double)(b->tv_nsec - a->tv_nsec) * 1e-9;
}

/* ----------------------------------------------------------------------- */
/* verify_output                                                             */
/* ----------------------------------------------------------------------- */

static int verify_output(void)
{
    const double eps_rel = 1e-9;
    const double eps = eps_rel * sqrt(EXPECTED_REAL * EXPECTED_REAL
                                       + EXPECTED_IMAG * EXPECTED_IMAG);

    printf("\n--- Verifying output ---\n");
    printf("  Expected: %.4f + %.4fi  (all elements)\n",
           EXPECTED_REAL, EXPECTED_IMAG);

    hid_t fc = H5Fopen(FILE_C, H5F_ACC_RDONLY, H5P_DEFAULT);
    if (fc < 0) {
        fprintf(stderr, "verify: cannot open %s\n", FILE_C);
        return -1;
    }
    hid_t dset_C = dset_open_no_cache(fc, DSET);
    if (dset_C < 0) {
        fprintf(stderr, "verify: cannot open dataset %s\n", DSET);
        H5Fclose(fc);
        return -1;
    }

    TensorRegistry *reg_C = registry_create_from_dset(dset_C);
    if (!reg_C) {
        fprintf(stderr, "verify: registry_create_from_dset failed\n");
        H5Dclose(dset_C); H5Fclose(fc);
        return -1;
    }
    if (registry_scan_file(dset_C, reg_C) < 0) {
        fprintf(stderr, "verify: registry_scan_file failed\n");
        registry_destroy(reg_C); H5Dclose(dset_C); H5Fclose(fc);
        return -1;
    }

    int rank = reg_C->rank;
    printf("  C grid: ");
    size_t total_tiles = 1;
    for (int d = 0; d < rank; d++) {
        printf("%s%llu", (d ? "×" : ""), (unsigned long long)reg_C->grid_dims[d]);
        total_tiles *= (size_t)reg_C->grid_dims[d];
    }
    printf("  (%zu tiles total)\n", total_tiles);

    hid_t h5ctype = create_h5_complex_type();
    if (h5ctype < 0) {
        fprintf(stderr, "verify: create_h5_complex_type failed\n");
        registry_destroy(reg_C); H5Dclose(dset_C); H5Fclose(fc);
        return -1;
    }

    size_t elems = 1;
    for (int d = 0; d < rank; d++)
        elems *= (size_t)reg_C->chunk_dims[d];

    double _Complex *buf = malloc(elems * sizeof(double _Complex));
    if (!buf) {
        fprintf(stderr, "verify: malloc failed\n");
        H5Tclose(h5ctype);
        registry_destroy(reg_C); H5Dclose(dset_C); H5Fclose(fc);
        return -1;
    }

    /* Sample tiles: corner, all-last, centre. */
    hsize_t samples[3][8];  /* up to rank-8 */
    memset(samples[0], 0, sizeof(samples[0]));
    for (int d = 0; d < rank; d++)
        samples[1][d] = reg_C->grid_dims[d] - 1;
    for (int d = 0; d < rank; d++)
        samples[2][d] = reg_C->grid_dims[d] / 2;

    int total_fail = 0;

    for (int si = 0; si < 3; si++) {
        hsize_t *coord = samples[si];

        TileMetadata *m = registry_get_tile(reg_C, coord);
        if (!m || m->status != TILE_STATUS_ON_DISK) {
            fprintf(stderr, "verify: tile not on disk (sample %d)\n", si);
            total_fail++;
            continue;
        }

        /* Pre-poison. */
        for (size_t i = 0; i < elems; i++)
            buf[i] = CMPLX(-1e30, -1e30);

        if (read_chunk_typed(dset_C, m->phys_offset, buf,
                             sizeof(double _Complex), rank,
                             reg_C->chunk_dims, h5ctype) < 0) {
            fprintf(stderr, "verify: read_chunk_typed failed (sample %d)\n", si);
            total_fail++;
            continue;
        }

        /* Physical extents. */
        hsize_t act[8];
        for (int d = 0; d < rank; d++) {
            hsize_t end = m->phys_offset[d] + reg_C->chunk_dims[d];
            act[d] = (end > reg_C->global_dims[d])
                     ? reg_C->global_dims[d] - m->phys_offset[d]
                     : reg_C->chunk_dims[d];
        }

        /* Flatten over physical extents for rank-N. */
        size_t strides[8];
        strides[rank - 1] = 1;
        for (int d = rank - 2; d >= 0; d--)
            strides[d] = strides[d + 1] * (size_t)reg_C->chunk_dims[d + 1];

        double max_re_err = 0.0, max_im_err = 0.0;
        size_t mismatch = 0;

        /* Iterate over the physical elements using an odometer. */
        size_t coords[8];
        size_t extents[8];
        memset(coords, 0, (size_t)rank * sizeof(size_t));
        for (int d = 0; d < rank; d++)
            extents[d] = (size_t)act[d];

        do {
            size_t idx = 0;
            for (int d = 0; d < rank; d++)
                idx += coords[d] * strides[d];

            double re = creal(buf[idx]);
            double im = cimag(buf[idx]);
            double re_err = fabs(re - EXPECTED_REAL);
            double im_err = fabs(im - EXPECTED_IMAG);
            if (re_err > max_re_err) max_re_err = re_err;
            if (im_err > max_im_err) max_im_err = im_err;
            if ((re_err > eps || im_err > eps) && mismatch == 0) {
                fprintf(stderr,
                        "  MISMATCH sample %d: got %.6f+%.6fi "
                        "expected %.4f+%.4fi\n",
                        si, re, im, EXPECTED_REAL, EXPECTED_IMAG);
            }
            if (re_err > eps || im_err > eps) mismatch++;

            /* Odometer step. */
            int carry = 1;
            for (int d = rank - 1; d >= 0 && carry; d--) {
                coords[d]++;
                if (coords[d] < extents[d]) carry = 0;
                else                        coords[d] = 0;
            }
            if (carry) break;  /* wrapped = done */

        } while (coords[0] != 0 || coords[1] != 0);  /* reinvented, see below */

        /*
         * The inline odometer above doesn't perfectly signal termination
         * for rank > 2.  Use a simpler flat-element loop instead.
         */
        /* Reset and redo with a flat loop for clarity. */
        max_re_err = 0.0; max_im_err = 0.0; mismatch = 0;
        size_t total_elems = 1;
        for (int d = 0; d < rank; d++) total_elems *= extents[d];

        /* Build row-major flat → multi-index mapping directly. */
        for (size_t flat = 0; flat < total_elems; flat++) {
            /* Multi-index of 'flat' in 'extents[]' array. */
            size_t idx = 0;
            size_t rem = flat;
            /* Compute physical strides over extents (not chunk_dims). */
            size_t ext_strides[8];
            ext_strides[rank - 1] = 1;
            for (int d = rank - 2; d >= 0; d--)
                ext_strides[d] = ext_strides[d + 1] * extents[d + 1];
            for (int d = 0; d < rank; d++) {
                size_t coord_d = rem / ext_strides[d];
                rem %= ext_strides[d];
                /* Buffer uses chunk_dims (nominal) strides. */
                idx += coord_d * strides[d];
            }

            double re = creal(buf[idx]);
            double im = cimag(buf[idx]);
            double re_err = fabs(re - EXPECTED_REAL);
            double im_err = fabs(im - EXPECTED_IMAG);
            if (re_err > max_re_err) max_re_err = re_err;
            if (im_err > max_im_err) max_im_err = im_err;
            if ((re_err > eps || im_err > eps) && mismatch == 0) {
                fprintf(stderr,
                        "  MISMATCH sample %d element %zu: "
                        "got %.6f+%.6fi  expected %.4f+%.4fi\n",
                        si, flat, re, im, EXPECTED_REAL, EXPECTED_IMAG);
            }
            if (re_err > eps || im_err > eps) mismatch++;
        }

        int tile_fail = (mismatch > 0);
        total_fail += tile_fail;

        /* Print tile coords. */
        printf("  tile(");
        for (int d = 0; d < rank; d++)
            printf("%s%llu", (d ? "," : ""), (unsigned long long)coord[d]);
        printf(")  act(");
        for (int d = 0; d < rank; d++)
            printf("%s%llu", (d ? "×" : ""), (unsigned long long)act[d]);
        printf(")  max_err=(%.2e,%.2e)  %s\n",
               max_re_err, max_im_err,
               tile_fail ? "FAIL" : "PASS");
    }

    free(buf);
    H5Tclose(h5ctype);
    registry_destroy(reg_C);
    H5Dclose(dset_C);
    H5Fclose(fc);

    return (total_fail > 0) ? -1 : 0;
}

/* ----------------------------------------------------------------------- */
/* main                                                                      */
/* ----------------------------------------------------------------------- */

int main(void)
{
    printf("=== Small Complex Contraction Benchmark ===\n");
    printf("Expression : ijab,akbl->klji\n");
    printf("Dtype      : COMPLEX128\n");
    printf("Global dim : %d per index\n", SMALL_DIM);
    printf("Chunk side : %d per index\n", SMALL_CHUNK);
    printf("Pool cap   : %d MiB (forces out-of-core)\n\n", POOL_CAP_MB);

    double elems_per_tensor = 1.0;
    for (int i = 0; i < 4; i++) elems_per_tensor *= SMALL_DIM;
    double mib_per_tensor = elems_per_tensor * 16.0 / (1024.0 * 1024.0);
    printf("Tensor : %.1f MiB each\n", mib_per_tensor);

    double total_flops = 8.0;
    for (int i = 0; i < 6; i++) total_flops *= (double)SMALL_DIM;
    printf("FLOPs  : %.3e\n\n", total_flops);

    /* Check input files. */
    {
        FILE *fa = fopen(FILE_A, "rb");
        FILE *fb = fopen(FILE_B, "rb");
        int missing = (!fa || !fb);
        if (fa) fclose(fa);
        if (fb) fclose(fb);
        if (missing) {
            fprintf(stderr,
                    "Input files not found.  Generate them first:\n"
                    "  ./build/gen_complex_tensor %d %d small\n",
                    SMALL_DIM, SMALL_CHUNK);
            return 1;
        }
    }

    /* Cap the memory pool. */
    char pool_cap_str[32];
    snprintf(pool_cap_str, sizeof(pool_cap_str), "%d", POOL_CAP_MB);
    setenv("TENSOR_POOL_MB", pool_cap_str, 1);
    printf("TENSOR_POOL_MB=%s MiB\n\n", pool_cap_str);

    /* Run. */
    printf("--- Running contraction ---\n");
    struct timespec t0, t1;
    clock_gettime(CLOCK_MONOTONIC, &t0);

    int ret = run_contraction_einsum(
        "ijab,akbl->klji",
        FILE_A, DSET,
        FILE_B, DSET,
        FILE_C, DSET);

    clock_gettime(CLOCK_MONOTONIC, &t1);
    double elapsed = elapsed_s(&t0, &t1);

    if (ret != 0) {
        fprintf(stderr, "Contraction failed.\n");
        return 1;
    }

    double gflops  = (total_flops / elapsed) / 1e9;
    double read_mib = 2.0 * mib_per_tensor;
    double bw_mibs  = read_mib / elapsed;

    printf("\n--- Performance ---\n");
    printf("  Elapsed   : %.3f s\n",    elapsed);
    printf("  Sustained : %.2f GFLOPS\n", gflops);
    printf("  I/O read  : %.1f MiB  →  %.1f MiB/s\n", read_mib, bw_mibs);

    /* Verify. */
    ret = verify_output();
    printf("\n=== Result: %s ===\n", ret ? "FAILED" : "ALL PASSED");
    return ret ? 1 : 0;
}
