/*
 * tests/test_mixed_rank.c
 *
 * C driver for the mixed-rank COMPLEX128 contraction test:
 *
 *   abcde,cfeg->abdfg   (rank-5 × rank-4 → rank-5)
 *
 * Input files are generated by tests/verify_mixed_rank.py:
 *   build/A_mixed.h5  — dataset "tensor", shape (DIM,)*5, compound {r,i}
 *   build/B_mixed.h5  — dataset "tensor", shape (DIM,)*4, compound {r,i}
 *
 * This driver calls run_contraction_einsum and writes the result to:
 *   build/C_mixed.h5  — dataset "tensor"
 *
 * Exit status: 0 on success, 1 on error.
 */

#include "engine.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Resolve build-relative paths from the working directory. */
#define FILE_A  "build/A_mixed.h5"
#define FILE_B  "build/B_mixed.h5"
#define FILE_C  "build/C_mixed.h5"
#define DSET    "tensor"
#define EXPR    "abcde,cfeg->abdfg"

int main(void)
{
    printf("=================================================================\n");
    printf("  Mixed-Rank COMPLEX128 Contraction Driver\n");
    printf("  Expression : %s\n", EXPR);
    printf("  A file     : %s\n", FILE_A);
    printf("  B file     : %s\n", FILE_B);
    printf("  C file     : %s\n", FILE_C);
    printf("=================================================================\n");

    int rc = run_contraction_einsum(EXPR,
                                    FILE_A, DSET,
                                    FILE_B, DSET,
                                    FILE_C, DSET);
    if (rc != 0) {
        fprintf(stderr, "run_contraction_einsum failed (rc=%d)\n", rc);
        return 1;
    }

    printf("\n");
    printf("=================================================================\n");
    printf("  Engine finished — output written to %s\n", FILE_C);
    printf("  Return to the Python verifier and press Enter.\n");
    printf("=================================================================\n");
    return 0;
}
